name: Create tag
on:
  workflow_run:
    workflows: ["Detect Project Language and Version"]
    types:
      - completed
  workflow_call:
    outputs:
      tag_name:
        description: "Created tag name"
        value: ${{ jobs.create_tag.outputs.tag_name }}
  workflow_dispatch:

jobs:
  create_tag:
    needs: [detect_version]
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.create_tag.outputs.tag_name }}
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create and push Git tag
        id: create_tag
        env:
          VERSION: ${{ needs.detect_version.outputs.project_version }}
        run: |
          if [ -z "$VERSION" ]; then
            echo "Error: VERSION is not set."
            exit 1
          fi

          TAG_NAME="v${VERSION}"
          echo "Creating tag $TAG_NAME"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Check if the tag exists
          if git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
            echo "Tag $TAG_NAME already exists. Overwriting..."
          fi

          git tag -f -a $TAG_NAME -m "Release $TAG_NAME"
          git push origin -f $TAG_NAME

          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
