name: Detect Project Language and Version

on:
  workflow_call:
  workflow_dispatch:

jobs:
  detect_language_and_version:
    runs-on: ubuntu-latest

    outputs:
      language: ${{ steps.detect_language.outputs.project_language }}
      version: ${{ steps.detect_version.outputs.project_version }}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Detect language 
        id: detect_language
        run: |
          if [[ -f "pom.xml" ]]; then
            LANGUAGE="java"
          elif [[ -f "package.json" ]]; then
            LANGUAGE="javascript"
          else
            LANGUAGE="other"
          fi
          
          echo "language=$LANGUAGE" >> $GITHUB_OUTPUT

      - name: Detect version 
        id: detect_version
        run: |
          if [[ "${{ steps.detect_language_and_version.outputs.language }}" == "java" ]]; then
            echo "Java project detected. Performing Java-specific actions..."
            VERSION=$(xmllint --xpath "//*[local-name()='project']/*[local-name()='version']/text()" pom.xml)
          elif [[ "${{ steps.detect_language_and_version.outputs.language }}" == "javascript" ]]; then
            echo "JavaScript project detected. Performing JavaScript-specific actions..."
            VERSION=$(jq -r '.version' package.json)
          else
            echo "No specific actions defined for this project type."
            VERSION="1.0.0"
          fi
          
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "Detected version: $VERSION"
      
      - name: Display project language & version
        run: | 
          echo "Project Language: ${{ steps.detect_language.outputs.language }}"
          echo "Project Version: ${{ steps.detect_version.outputs.version }}"
