name: Detect Project Language and Version
on:
  workflow_call:
  workflow_dispatch:

jobs:
  detect_language:
    runs-on: ubuntu-latest
    outputs:
      project_language: ${{ steps.detect_language.outputs.project_language }}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Detect language 
        id: detect_language
        run: |
          if [[ -f "pom.xml" ]]; then
            PROJECT_LANGUAGE="java"
          elif [[ -f "package.json" ]]; then
            PROJECT_LANGUAGE="javascript"
          else
            PROJECT_LANGUAGE="other"
          fi
          
          echo "project_language=${PROJECT_LANGUAGE}" >> $GITHUB_OUTPUT

  detect_version:
    needs: detect_language  
    runs-on: ubuntu-latest
    outputs:
      project_version: ${{ steps.detect_version.outputs.project_version }}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install required tools
        run: |
          if [[ -f "pom.xml" ]]; then
            sudo apt-get update
            sudo apt-get install -y libxml2-utils
          elif [[ -f "package.json" ]]; then
            sudo apt-get update
            sudo apt-get install -y jq
          fi

      - name: Detect version 
        id: detect_version
        run: |
          if [[ "${{ steps.detect_language.outputs.project_language }}" == "java" ]]; then
            echo "Java project detected. Extracting version from pom.xml..."
            PROJECT_VERSION=$(xmllint --xpath "//*[local-name()='project']/*[local-name()='version']/text()" pom.xml)
          elif [[ "${{ steps.detect_language.outputs.project_language }}" == "javascript" ]]; then
            echo "JavaScript project detected. Extracting version from package.json..."
            PROJECT_VERSION=$(jq -r '.version' package.json)
          else
            echo "No specific version detection for this project type."
            PROJECT_VERSION="1.0.0"
          fi
          
          echo "project_version=${PROJECT_VERSION}" >> $GITHUB_OUTPUT

  display_lang_and_version:
    needs: [detect_language, detect_version]  
    runs-on: ubuntu-latest
    steps:
      - name: Display project language & version
        run: | 
          echo "Project Language: ${{ steps.detect_language.outputs.project_language }}"
          echo "Project Version: ${{ steps.detect_version.outputs.project_version }}"
