name: Detect Project Language and Version
on:
  workflow_call:
    outputs:
      project_language:
        description: "Detected project language"
        value: ${{ jobs.detect_language.outputs.project_language }}
      project_version:
        description: "Detected project version"
        value: ${{ jobs.detect_version.outputs.project_version }}
  workflow_dispatch:
jobs:
  detect_language:
    runs-on: ubuntu-latest
    outputs:
      project_language: ${{ steps.detect_language.outputs.project_language }}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Detect language 
        id: detect_language
        run: |
          if [[ -f "pom.xml" ]]; then
            PROJECT_LANGUAGE="java"
          elif [[ -f "package.json" ]]; then
            PROJECT_LANGUAGE="javascript"
          else
            PROJECT_LANGUAGE="other"
          fi
          
          echo "project_language=${PROJECT_LANGUAGE}" >> $GITHUB_OUTPUT
  detect_version:
    needs: detect_language  
    runs-on: ubuntu-latest
    outputs:
      project_version: ${{ steps.detect_version.outputs.project_version }}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Cache tools
        id: cache-tools
        uses: actions/cache@v4.2.0
        with:
          path: |
            /usr/bin/xmllint
            /usr/bin/jq
          key: ${{ runner.os }}-tools-${{ hashFiles('pom.xml', 'package.json') }}
          restore-keys: |
            ${{ runner.os }}-tools-
      - name: Install required tools
        if: steps.cache-tools.outputs.cache-hit != 'true'
        run: |
          if [[ -f "pom.xml" ]]; then
            echo "Installing libxml2-utils..."
            sudo apt-get update
            sudo apt-get install -y libxml2-utils
          elif [[ -f "package.json" ]]; then
            echo "Installing jq..."
            sudo apt-get update
            sudo apt-get install -y jq
          fi
      - name: Detect version 
        id: detect_version
        run: |
          if [[ "${{ needs.detect_language.outputs.project_language }}" == "java" ]]; then
            echo "Java project detected. Extracting version from pom.xml..."
            PROJECT_VERSION=$(xmllint --xpath "//*[local-name()='project']/*[local-name()='version']/text()" pom.xml)
          elif [[ "${{ needs.detect_language.outputs.project_language }}" == "javascript" ]]; then
            echo "JavaScript project detected. Extracting version from package.json..."
            PROJECT_VERSION=$(jq -r '.version' package.json)
          else
            echo "No specific version detection for this project type."
            PROJECT_VERSION="1.0.0"
          fi
          
          echo "project_version=${PROJECT_VERSION}" >> $GITHUB_OUTPUT
  display_language_and_version:
    needs: [detect_language, detect_version]  
    runs-on: ubuntu-latest
    steps:
      - name: Display project language & version
        run: | 
          echo "Project Language: ${{ needs.detect_language.outputs.project_language }}"
          echo "Project Version: ${{ needs.detect_version.outputs.project_version }}"
