name: Commit Checks

on:
  workflow_call:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  check_commit:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate Commit Message
        id: validate_commit
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=format:%s)
          REGEX="^(feat|fix|docs|style|refactor|test|chore): .+$"
          if [[ ! "$COMMIT_MESSAGE" =~ $REGEX ]]; then
            echo "Invalid commit message: '$COMMIT_MESSAGE'"
            echo "Commit message must match the regex: $REGEX"
            exit 1
          fi
          echo "Commit message validated successfully: '$COMMIT_MESSAGE'"
